### ISSUE TITLE
Fix maven build warning

### ISSUE THREAD

**Issue by jncornett** [Bekreth/jetedge#21]
I get the following warning when running `mvn clean install`:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.rainbowpunch:jetedge:jar:0.8.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 58, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

**Comment by Bekreth** [comment]
The fix meant to repair this caused the entire build to start failing due to the following class not being found. org/codehaus/plexus/languages/java/jpms/LocationManager

**Comment by jncornett** [comment]
What is the root cause of this issue?

**Comment by wriiblo** [comment]
Strange. It works fine in my machine. @jncornett do you mind checking out e234fbd commit and building it from there? I am wanting to make sure whether this is an issue on my machine or @Bekreth's machine

**Comment by wriiblo** [comment]
@jncornett It's complaining that the version of maven-compiler-plugin is not explicitly stated. Maven will do some resolution on its part in order to pick the right version which is more brittle.

**Comment by jncornett** [comment]
Building with `mvn clean install` for
https://github.com/Bekreth/jetedge/commit/e234fbdabfe038cbfff3a68a3057cf89f45c4223
works for me. I'm actually not sure why that commit was reverted, did it break for you @Bekreth?

**Comment by Bekreth** [comment]
It did previously.  Not sure why.  I'll recommit it.

**Comment by Bekreth** [comment]
https://github.com/Bekreth/jetedge/pull/37
