### ISSUE TITLE
Enable travis CI builds

### ISSUE THREAD

**Issue by jncornett** [Bekreth/jetedge#24]
Enable travis CI builds so any breaking changes will be obvious to users. https://travis-ci.org/Bekreth/java-test-data-generator

**Comment by Bekreth** [comment]
First, have to have tests that can actually catch broken things.

**Comment by jncornett** [comment]
At least, broken builds will show up. I would do this myself, but I can't because I'm not the owner of the repository/github account.

**Comment by Bekreth** [comment]
https://github.com/Bekreth/jetedge/pull/38
