### ISSUE TITLE
Create standard test pojo

### ISSUE THREAD

**Issue by Bekreth** [Bekreth/jetedge#31]
Currently, there are several different test pojos that exist.  We should reduce this down to a single pojo that will allow for exhaustive testing.

Features the Pojo should have:
* Hierarchy made  predominantly of data that is populated with default limiters.
* Lists of both single primitive and of deeper Pojos
* A Pojo that is made of standard data types that there aren't default limiters for (BigInt, Date, etc...)
* Multiple extensions from a single super class that are used
* Extensions of abstract classes and interfaces

The core of this test Pojo should be of the simple case of primitives and and compositions.  The additional, more difficult structures, should be added in through compositions that are easy to ignore.

**Comment by jncornett** [comment]
I actually think we should do the opposite and have each test class define its own test pojos. This way, (1) pojos will be close to the unit tests (in the same test class) and (2) pojos will not be overly "noisy" and easier to understand in the context of the current, failing test.
