### ISSUE TITLE
Feature proposal: Setting arbitrary depth child limiters.

### ISSUE THREAD

**Issue by jncornett** [Bekreth/jetedge#33]
The nested limiter syntax is a bit awkward. I propose a dot-separated syntax for setting limiters at an arbitrary depth. Example:

```
new PojoGeneratorBuilder<>(MyCompoundPojo.class)
        .andLimitField("foo.bar.buzz", rng -> rng::nextInt)
        .andLimitField("*", (Limiter<String>)rng -> "defaultValue")
        .build();
```

**Comment by Bekreth** [comment]
I like this a lot better than the current setup.

**Comment by Bekreth** [comment]
https://github.com/Bekreth/jetedge/pull/44
