### ISSUE TITLE
Create a Limiter the reads data from a file

### ISSUE THREAD

**Issue by Bekreth** [Bekreth/jetedge#61]
Title says it all.  Something like

```
new DataFromFileLimiter(String fileLocation);
new DataFromFileLimiter(String fileLocation, String delimiter);
```

**Comment by trevershick** [comment]
Two questions.  What sort of file format(s) should be supported?
One line per value?  CSV?
Should the limiter 'wrap around' the file?  Meaning, if the EOF is reached should it throw an exception or just use the file contents as the full list of acceptable values?

**Comment by Bekreth** [comment]
The limiter should take in a deserialization method to convert the file's string into POJOs to allow the user to define how the data should be read.  The entire file should be read and in used as the seed for an `ObjectLimiter`.  Each element being a possible value  to be populated into the limited field.

**Comment by Bekreth** [comment]
Following discussions some discussion, it's clear that Jetedge shoulnd't worry about reading files and trust users to be able to read their own file.s
