### ISSUE TITLE
Upgrade FloatLimiter

### ISSUE THREAD

**Issue by Bekreth** [Bekreth/jetedge#96]
Float Limiter needs some love.

**Comment by trevershick** [comment]
What sort of features are you looking for?

**Comment by Bekreth** [comment]
The simple constructor for this class should look roughly like this
```
FloatLimiter(int range, int offset, int precision);
```
Where precision is the number of digits after the decimal place (should be allowed to take negative for number with zeros before the decimal such as 100, 5600, etc...)

**Comment by Bekreth** [comment]
https://github.com/Bekreth/jetedge/pull/126#pullrequestreview-120453928
